---
title: "lab2"
author: "Gavin Hyde"
date: "2/16/2022"
output: html_document
---

choco <- read.csv("https://ds202-at-isu.github.io/labs/data/choco.csv")
head(choco)

choco %>% ggplot(aes(x = as.factor(Review.Date))) + geom_bar()


Question Set I 

1. What is the overall number of chocolate bars rated?
1852 chocolate bars were rate, under the assumption each row represents an individual chocolate bar.
```{r}
nrow(choco)
```

2. How does the number of ratings depend on the year? Draw a bar chart of the number of reports.

ggplot(data = choco, aes(x = Review.Date)) + 
  geom_bar() +
  scale_x_continuous(breaks = c(2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017))

Question Set II 

1. How are ratings distributed? Draw a histogram of ratings and describe it. Don’t forget to mention outliers, if there are any.

ggplot(data = choco, aes(x = Rating)) +
  geom_histogram()

It seems like most of the reviews are between 3 and 4, with the majority of those around 3.5., outlierfs are very few reviews at 1 and 5. 

2. Do ratings depend on the cocoa percentage of a chocolate bar?

ggplot(data = choco, aes(x = Rating, y = Cocoa.Pct)) +
  geom_jitter()
  
There seems to be very correlation between the two. The range of normal seems to be around between 60% and 80% of cocoa, and a rating between 2.5 and 4. Anything outside of that seems to be an outlier, that's the heaviest correlation.

3. How do ratings compare across different company locations? Focus on the three locations with the most ratings:
